### PR TITLE
Add demo image and shapes

### PR DESCRIPTION
**Pull request by teozec**
This PR adds some basic geometric shapes, as well as a demo functionality to render a default image.

- [x] Shape
- [x] Sphere
- [x] Sphere test
- [x] Plane
- [x] Plane test
- [x] World
- [x] World test
- [x] Demo

### CODE REVIEW

**Comment by ngrlcu** [comment]
I believe its just a matter of defining an assignment operator in `HitRecord` struct

**Comment by ngrlcu** [comment]
I added assignment operators on all the required structs (Points, Vecs, rays etc...). The main problem was instead the impossibility of passing a Shape object to `make_shared<>` so for now there is only the chance of adding Spheres to Worlds but we will improve it.

**Comment by teozec** [comment]
I am not sure the demo is correct, since the other four spheres of the cube are not visible. But is is a good starting point.

demo image

**Comment by teozec** [comment]
We need to understand how to handle `(u, v)` coordinates in CSG objects.

**Comment by ngrlcu** [comment]
I believe we have all set now. You can open a different PR for CSG implementation.

**Pull request merged**
