### PR TITLE
Geometry

### PR DESCRIPTION
**Pull request by ngrlcu**
This PR implements geometry objects:

- [x]  Point struct implementation
- [x]  Vec struct implementation
- [x]  Point test
- [x]  Vec test
- [x]  Transformation struct implementation
- [x]  Functions for common transformations
- [x]  Transformation test
- [x]  Common transformation functions test

### CODE REVIEW

**Comment by teozec** [comment]
I have added tests for the `Vec` type, and it seems that the `Vec::norm()` function is not working properly (or maybe I made some errors in the tests). Let's try to fix this.

**Comment by ngrlcu** [comment]
Tried with basic norm and passes the test. Looks like we are not allowed to "use" the output of norm() for calculations.

**Comment by teozec** [comment]
I changed the test removing the  `sqrt`. I don't understand why printing `a.norm()*a.norm()` gives `14`, but `assert(_areClose(a.norm()*a.norm(), 14.f, epsilon));` fails, we'll need to investigate.

**Comment by ngrlcu** [comment]
Printing the norm and the raw square root of the squared norm gives 3.74166. This means we do not have a precision higher then 1e-5: we must set the _areClose epsilon to this value instead of the usual 1e-10. This solved the problem

**Comment by teozec** [comment]
The same precision problem arises when testing for equality of rotated `Vec`s. Maybe we could increase the default epsilon in `Vec::operator==`, because the current value of 1e-10f seems to be too small to be useful.

**Comment by ngrlcu** [comment]
The `Transformation::operator==()` overloding was using an epsilon of order e-10 so i changed it to e-5 because of the same recurrent problem. On the same line of thoughts i changed the `Transformation::isConsistent()` function in order to make use of the same modification of code.

**Comment by ngrlcu** [comment]
I added `Transformation::areTransformationsClose()` in order to pass the epsilon parameter as a parameter in more methods.
Unfortunately it seems the inverse of matrices doesn't have constant precision.

**Pull request merged**
