### PR TITLE
Implement stacking of pfm images

### PR DESCRIPTION
**Pull request by teozec**
This PR aims at implementing a feature to combine (_stack_) different pfm images representing the same scene, in order to reduce the noise.

- [x] Mean stacking
- [x] Median stacking
- [x] Sigma clipping

### CODE REVIEW

**Comment by teozec** [comment]
It seems to be working fine.

Without stacking
demo-1

Stacking 30 images
stack

The black line is strange, could it be caused by a bias in the PCG?

**Comment by ngrlcu** [comment]
> The black line is strange, could it be caused by a bias in the PCG?

It might be for a linear increment of the seed...but i'm not sure.

**Comment by teozec** [comment]
I tried using the first 30 Fibonacci numbers as seed, and the black line is still present in a different position... In the median image it is not present, but the image itself is not very good. I am not sure if it is a bug in the implementation or the median method is not good for this scene.

Mean:
mean

Median:
median

**Comment by ngrlcu** [comment]
> The median image [...] is not very good. I am not sure if it is a bug in the implementation or the median method is not good for this scene.

The median is not optimal for a low illuminated scene: the darker regions are basically where is less likely to be illuminated. In the mean stack it turns out in a shadow; on the other hand, in the median stack is just more likely to be just not illuminated. So i believe it all works as expected.

**Comment by teozec** [comment]
I have added sigma clipping. The ending condition is simply a certain number of iterations specified by the users; maybe we can also provide a different condition, for example that the sigma does not vary more than a certain threshold from one iteration to the next.

I tried stacking ~50 images with 4 iterations of clipping and an alpha value of 2 (i.e. remove everything farther than 2 sigma over or under the median), and the clipped values were about 1/4 of the total. It seems a little too high, but probably it is caused by using a threshold of 2 sigma, which is quite small.

**Comment by teozec** [comment]
> maybe we can also provide a different condition, for example that the sigma does not vary more than a certain threshold from one iteration to the next.

Thinking a little more about this, it is probably not very useful, since there is a different sigma for each pixel and the condition would be reached after a different number of iterations for different pixels.

**Pull request merged**
