### PR TITLE
Add scenefile parser

### PR DESCRIPTION
**Pull request by teozec**
This PR aims at adding support for custom scenes defined in text files.

- [x] Lexer
- [x] Syntax analyzer
- [x] Render action

### CODE REVIEW

**Comment by teozec** [comment]
I implemented `parseScene` and the `render` function, but running with an example scenefile gives a segmentation fault during the execution of `parseScene`. More debugging is needed.

**Comment by ngrlcu** [comment]
Commenting out `parseTransformation()` and passing identity transformation by default works pretty well. I wrote a simple `test.txt` file that create a scene with just a sphere in the origin and the camera pointing along x-axis (since no transformation available for now).

This is the result of 
`./image-renderer render ../examples/test.txt`
converted into png:
render

So the problem appears to be `parseTransformation()`, let's dig in into it.

**Comment by teozec** [comment]
`parseTransformation()` does not cause segmentation faults or unexpected `GrammarError`s anymore. However, the image resulting rendering `examples/scene.txt` is pretty weird...

render

**Comment by teozec** [comment]
I changed the scene in `scene.txt` so that we can compare it with the `demo` scene. It seems that the parser makes every BRDF specular.

demo:
demo

scene.txt:
render

**Comment by teozec** [comment]
Remember kids: if you don't put a `break` statement, you will fall through the next `case` label. This may not be what you want...

This seems fixed, we can probably focus on adding support for CSG and other features of the renderer in the scenefile language.
render

**Comment by teozec** [comment]
Everything seems ok, and we also have an Italian Cornell box. I think we are ready to merge!

cornell

**Pull request merged**
