### PR TITLE
More on materials

### PR DESCRIPTION
**Pull request by ngrlcu**
This WIP aims to implement more features regarding materials.

- [x]  `roughness` parameter for `SpecularBRDF`
- [x]  dielectric material (with roughness)
- [x]  Perlin noise for some texture

### CODE REVIEW

**Comment by ngrlcu** [comment]
Roughness is working properly: on the right a sphere almost perfectly specular (roughness set to 0.05) and on the left a sphere with roughness equals to 0.75.
WhatsApp Image 2021-06-29 at 14 57 42

**Comment by ngrlcu** [comment]
The result seems right, i guess the fringing is just a matter of aliasing. 
glass

Up next TODO: adding reflection and roughness to it

**Comment by ngrlcu** [comment]
The dielectric looks almost perfect. Here an example of a glass sphere
glass

And here another example of a red-glass one
glass

**Comment by ngrlcu** [comment]
Here a sum up image of materials implemented
demo

**Comment by ngrlcu** [comment]
Still noticing annoying bands due to multithread:
materials2
Removing them from the pixel rendering and keeping it only for antialiasing (which has average operation in it) looks way better:
materials3

**Comment by ngrlcu** [comment]
From the original java [implementation](https://cs.nyu.edu/~perlin/noise/) (Perlin, 2002) we implement a c++ version of it.
The references are [this](https://solarianprogrammer.com/2012/07/18/perlin-noise-cpp-11/) straight forward explanation, this [deeper insight](http://viclw17.github.io/2018/12/28/Perlin-Noise-Implementation/#more) and also an interesting [video](https://youtu.be/MJ3bvCkHJtE).

**Comment by teozec** [comment]
This is a great job! Can't wait to try all these new materials :smile:

**Comment by ngrlcu** [comment]
Here a little showcase:

stack

From left to right: marble, wood and noise.

**Pull request merged**
