### PR TITLE
Antialiasing

### PR DESCRIPTION
**Pull request by ngrlcu**
This WIP is for the implementation of the anti-aliasing.

https://user-images.githubusercontent.com/79975678/120307596-757dd180-c2d3-11eb-93b7-4253596b2760.mp4

Here you can see the aliasing in the background.

### CODE REVIEW

**Comment by ngrlcu** [comment]
The anti-aliasing works pretty good. Here a demonstration:

Antialiasing demo

**Comment by teozec** [comment]
Great! Nice job. Maybe we should check that the number inputted by the user is a perfect square? Something like `areClose(sqrt(x), round(sqrt(x)))` (hoping that it works well with float arithmetic)? Either in an assert in the constructor or in the main.

**Comment by ngrlcu** [comment]
> Great! Nice job. Maybe we should check that the number inputted by the user is a perfect square? Something like `areClose(sqrt(x), round(sqrt(x)))` (hoping that it works well with float arithmetic)? Either in an assert in the constructor or in the main.

I did something like it in [this commit](https://github.com/teozec/image-renderer/pull/16/commits/d4e4562235110dbe5df2b77413a53048e5be1006).

**Comment by teozec** [comment]
Oops, sorry, I didn't notice it. I think it is ok then!

**Pull request merged**
