### PR TITLE
more shapes

### PR DESCRIPTION
**Pull request by ngrlcu**
This is a WIP for implementation of more Shape structs.

- [x] CSG Union
- [x] CSG Intersection
- [x] CSG Difference
- [x] Triangle
- [x] Box
- [x] Test CSG
- [x] Test Triangle
- [x] Test box

### CODE REVIEW

**Comment by ngrlcu** [comment]
The `hitPoint` on `Triangle` is incorrect due to the sign of `t`: previously I was taking the absolute value for it, but found it not proper and removed (since the error). I'm fixing it in the next commit changing the sign on `solution[2]` given by Cramer method.

**Comment by teozec** [comment]
The `Plane.isInner()` test fails on transformed planes, I am not sure why. We also need to understand what it means for a point on a triangle to be inner (we treat other shapes as 3D, but it is not evident what the triangle equivalent would be).

**Comment by teozec** [comment]
I had made a mistake in the test asserts, it should now be ok.

**Comment by ngrlcu** [comment]
> We also need to understand what it means for a point on a triangle to be inner (we treat other shapes as 3D, but it is not evident what the triangle equivalent would be).

We know if a Point is inside the triangle iff `beta`, `gamma` and `alpha` (1-`beta`-`gamma`) are all positive.

**Comment by teozec** [comment]
In the demo, CSGDifference doesn't seem to work (the upper sphere is complete, but it should be a difference between two spheres). Maybe there is something wrong in demo, since the tests pass, or maybe the tests are not complete.

demo

**Comment by teozec** [comment]
There are still problems with Differences and Intersections when using scaling transformations, I think I should add some tests because I don't understand what is wrong in the code.

For example, this should be the intersection between two translated spheres, scaled by 0.5, but it seems like the eye of Sauron.

demo

**Comment by ngrlcu** [comment]
> There are still problems with Differences and Intersections when using scaling transformations, I think I should add some tests because I don't understand what is wrong in the code.
> 
> For example, this should be the intersection between two translated spheres, scaled by 0.5, but it seems like the eye of Sauron.
> 
> demo

With PR #12 the problem is solved. Check this out:
demo

**Comment by teozec** [comment]
This test shows that we need to consider more carefully the case of a Ray parallel to one of the coordinate axis (and thus to two of the faces of the box). The problem is also visible in the demo, which should contain a Box and a Sphere but is a one-color image.

demo

**Comment by teozec** [comment]
I fixed the problem with parallel rays, but the demo is still not working. I'll write more tests.

**Comment by teozec** [comment]
I don't see any obvious problem, so I think we are ready to merge.

demo

**Pull request merged**
